/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package login;


import adminfolder.admindash;
import adminfolder.userForm;
import config.dbConnector;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static login.registerform.passwordHash;
import userfolder.useer;

/**
 *
 * @author Sofia
 */
public class loginform extends javax.swing.JFrame {

    
    public loginform() {
        initComponents();
    }
    
    static String names;
    static String lastname;
    
    
public static boolean loginAcc(String username1, String password1){
        dbConnector connector = new dbConnector();
        try{
            String hash = passwordHash(password1);
            String query = "SELECT * FROM datanew WHERE username ='"+username1+"' AND password ='"+hash+"' AND status ='Active' ";
            ResultSet resultSet = connector.getData(query);
            
            if(resultSet.next()){
                
            names = resultSet.getString("f_name");
            lastname = resultSet.getString("l_name");
                return true;
                
            }else{
                return false;
            }
        }catch(SQLException e){
        return false;
        }
    
    }
    
    public static boolean isADMIN(String username) {
        dbConnector connector = new dbConnector();
        try {
            String query = "SELECT * FROM datanew WHERE username ='" + username + "' AND account_type ='Admin'";
            ResultSet resultSet = connector.getData(query);
            return resultSet.next();
        }catch(SQLException e) {
            System.out.println(""+e);
        return false;
        }
    }
    
    public static boolean isUser(String username) {
        dbConnector connector = new dbConnector();
        try {
            String query = "SELECT * FROM datanew WHERE username ='" + username + "' AND account_type ='User'";
            ResultSet resultSet = connector.getData(query);
            return resultSet.next();
        }catch(SQLException e) {
            System.out.println(""+e);
        return false;
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Registerformbutton = new javax.swing.JButton();
        pazz = new javax.swing.JTextField();
        uzer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        button = new javax.swing.JButton();
        exbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1431, 933));
        jPanel1.setPreferredSize(new java.awt.Dimension(1431, 933));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Username:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 90, 129, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Create an Account?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 200, 177, 22);

        Registerformbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Registerformbutton.setText("Register");
        Registerformbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegisterformbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegisterformbuttonMouseExited(evt);
            }
        });
        Registerformbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterformbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Registerformbutton);
        Registerformbutton.setBounds(220, 230, 89, 25);
        jPanel1.add(pazz);
        pazz.setBounds(310, 150, 163, 29);

        uzer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uzerActionPerformed(evt);
            }
        });
        jPanel1.add(uzer);
        uzer.setBounds(310, 90, 163, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Password:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 130, 124, 29);

        button.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        button.setText("Login");
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
        });
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        jPanel1.add(button);
        button.setBounds(420, 210, 71, 25);

        exbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exbutton.setText("Exit");
        exbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exbuttonMouseExited(evt);
            }
        });
        exbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(exbutton);
        exbutton.setBounds(350, 210, 59, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BERGEN SCHOLARSHIP UNIVERSITY");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 10, 490, 29);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\wangs\\Downloads\\pexels-thought-catalog-317580-904616.jpg")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 300));
        jLabel4.setMinimumSize(new java.awt.Dimension(500, 300));
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(4, 0, 3870, 874);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uzerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uzerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uzerActionPerformed

    private void RegisterformbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterformbuttonActionPerformed
        registerform ads = new registerform();
        ads.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterformbuttonActionPerformed

    private void RegisterformbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterformbuttonMouseExited
        Registerformbutton.setBackground(Color.white);
    }//GEN-LAST:event_RegisterformbuttonMouseExited

    private void RegisterformbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegisterformbuttonMouseEntered
        Registerformbutton.setBackground(Color.green);
    }//GEN-LAST:event_RegisterformbuttonMouseEntered

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        if (loginAcc(uzer.getText(), pazz.getText())) {
            String username = uzer.getText();
            if (isADMIN(username)) {
                JOptionPane.showMessageDialog(null, "Login Successfully as Admin");
                admindash ads = new admindash();
                ads.namess.setText(""+lastname);
                ads.lastname.setText(""+names);
                ads.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Login Successfully as User");
                useer uds = new useer();
                uds.namess.setText(""+names);
                uds.setVisible(true);
                this.dispose();
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Invalid User or Password");
        }
    }//GEN-LAST:event_buttonActionPerformed

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
        button.setBackground(Color.white);
    }//GEN-LAST:event_buttonMouseExited

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
        button.setBackground(Color.green);
    }//GEN-LAST:event_buttonMouseEntered

    private void exbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exbuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exbuttonActionPerformed

    private void exbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exbuttonMouseExited
        exbutton.setBackground(Color.white);
    }//GEN-LAST:event_exbuttonMouseExited

    private void exbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exbuttonMouseEntered
        exbutton.setBackground(Color.red);
    }//GEN-LAST:event_exbuttonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registerformbutton;
    private javax.swing.JButton button;
    private javax.swing.JButton exbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pazz;
    private javax.swing.JTextField uzer;
    // End of variables declaration//GEN-END:variables

}
