/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import adminfolder.admindash;
import config.dbConnector;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author wangs
 */
public class applicationform extends javax.swing.JFrame {

    /**
     * Creates new form applicationform
     */
    public applicationform() {
        initComponents();
    }
    
   public static String afsname, alsname;
    
    public boolean fname_alname(){
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM applicantstab WHERE fname ='"+afname.getText()+"' ";
            ResultSet resultSet = dbc.getData(query);
       
         
            if(resultSet.next()){
                afsname = resultSet.getString("fname");  
                if(afsname.equals(afname.getText())){
                    JOptionPane.showMessageDialog(null, "first name exist!");
                    alname.setText("");         
                } 
                return true;
            }else{
                return false;
            }
            
            
        
        }catch(SQLException e){
            System.out.println(""+e);
            return false;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ayear = new javax.swing.JTextField();
        afname = new javax.swing.JTextField();
        alname = new javax.swing.JTextField();
        anitial = new javax.swing.JTextField();
        aphone = new javax.swing.JTextField();
        aemailadd = new javax.swing.JTextField();
        aadress = new javax.swing.JTextField();
        amads = new javax.swing.JTextField();
        afads = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        agend = new javax.swing.JComboBox<>();
        statuz = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        uni1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(919, 591));
        setMinimumSize(new java.awt.Dimension(919, 591));
        setPreferredSize(new java.awt.Dimension(919, 591));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fathers Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(320, 210, 120, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gender:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(360, 290, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Lastname:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 210, 90, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Middle Initial:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 250, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone #:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 290, 90, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email Adress:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 340, 110, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adress:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 370, 90, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mothers Name:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(320, 170, 120, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Status:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(380, 370, 70, 22);
        jPanel2.add(ayear);
        ayear.setBounds(440, 250, 170, 26);
        jPanel2.add(afname);
        afname.setBounds(120, 170, 170, 26);
        jPanel2.add(alname);
        alname.setBounds(120, 210, 170, 26);
        jPanel2.add(anitial);
        anitial.setBounds(120, 250, 170, 26);
        jPanel2.add(aphone);
        aphone.setBounds(120, 290, 170, 26);

        aemailadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aemailaddActionPerformed(evt);
            }
        });
        jPanel2.add(aemailadd);
        aemailadd.setBounds(120, 330, 170, 26);

        aadress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadressActionPerformed(evt);
            }
        });
        jPanel2.add(aadress);
        aadress.setBounds(120, 370, 170, 26);

        amads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amadsActionPerformed(evt);
            }
        });
        jPanel2.add(amads);
        amads.setBounds(440, 170, 170, 26);
        jPanel2.add(afads);
        afads.setBounds(440, 210, 170, 26);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("BERGEN SCHOLARSHIP UNIVERSITY");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(80, 10, 470, 20);

        jButton1.setText("Add Applicants");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(420, 410, 140, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Year and course:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(300, 250, 150, 22);

        agend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel2.add(agend);
        agend.setBounds(440, 290, 81, 26);

        statuz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Approved" }));
        jPanel2.add(statuz);
        statuz.setBounds(450, 370, 100, 26);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FirstName:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 170, 90, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Scholarship type:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(300, 330, 150, 22);

        uni1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unifast", "Ched", "Smart" }));
        jPanel2.add(uni1);
        uni1.setBounds(450, 330, 80, 26);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Frontdesk ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(260, 40, 140, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 920, 590);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aemailaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aemailaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aemailaddActionPerformed

    private void amadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amadsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amadsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
        
        
        if(afname.getText().isEmpty() || alname.getText().isEmpty() 
                || anitial.getText().isEmpty() || aphone.getText().isEmpty() 
                || aemailadd.getText().isEmpty() || aadress.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "All fields are required!");
            
        }else{
        
        dbConnector dbc = new dbConnector();
        
        try{
            
            if(dbc.insertData("INSERT INTO applicantstab(fname, lname, middle_initial, contact_number, email_address, adress, mother_name, father_name, year_course, gender, scholarship_type)"
                + "Values ('"+afname.getText()+"', '"+alname.getText()+"', '"+anitial.getText()+"' , '"+aphone.getText()+"', '"+aemailadd.getText()+"', "
                        + " '"+aadress.getText()+"', '"+amads.getText()+"', '"+afads.getText()+"', '"+ayear.getText()+"', "
                        + " '"+agend.getSelectedItem()+"','"+agend.getSelectedItem()+"','"+statuz.getSelectedItem()+"' ) ")){ 
                JOptionPane.showMessageDialog(null, "Applicants Added");
        
            }else{
            
                JOptionPane.showMessageDialog(null, "Connection Error");
        }   
         
        
        
        }catch (HeadlessException e){
        
            System.out.println(e);
        
        }  
        this.dispose();     
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void aadressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aadressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(applicationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new applicationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadress;
    private javax.swing.JTextField aemailadd;
    private javax.swing.JTextField afads;
    private javax.swing.JTextField afname;
    private javax.swing.JComboBox<String> agend;
    private javax.swing.JTextField alname;
    private javax.swing.JTextField amads;
    private javax.swing.JTextField anitial;
    private javax.swing.JTextField aphone;
    private javax.swing.JTextField ayear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> statuz;
    private javax.swing.JComboBox<String> uni1;
    // End of variables declaration//GEN-END:variables
}
